api:
  autodiscoveryID: ""
  
accelerator:
  logger: "com.mulesoft.accelerator.saphana"

https:
  host: "0.0.0.0"
  port: "8082"
  
until:
  successful:
    maxretries: "3"
    timebetween: "3000"
  
sap:
  hana:
    url: ""
    getPayments:
      service: ""
      entityType: ""
    getPayment:
      service: ""
      entityType: ""
    
 